# Generated by Django 3.0.5 on 2020-05-11 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NHOM_SP',
            fields=[
                ('MaNhom', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenNhom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DANHMUC_SP',
            fields=[
                ('MaDM', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenDM', models.CharField(max_length=100)),
                ('MaNhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoitrang.NHOM_SP')),
            ],
        ),
    ]
