# Generated by Django 3.0.5 on 2020-05-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoitrang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SANPHAM',
            fields=[
                ('MASP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenSP', models.CharField(max_length=100)),
                ('Thuonghieu', models.CharField(max_length=50)),
                ('Kichco', models.CharField(max_length=5)),
                ('Mausac', models.CharField(max_length=50)),
            ],
        ),
    ]
