# Generated by Django 3.0.5 on 2020-05-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoitrang', '0002_sanpham'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='GiaBan',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanpham',
            name='Hdsd',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanpham',
            name='Hinhanh',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanpham',
            name='Mota',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanpham',
            name='Soluong',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
