# Generated by Django 3.0.5 on 2020-05-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoitrang', '0003_auto_20200511_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhom_sp',
            name='Hinhanh',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
