# Generated by Django 3.0.5 on 2020-05-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taikhoan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taikhoan',
        ),
    ]
